// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1R2W0BEh-6bm83SB7___O4HxJzGRwziU',
    appId: '1:162628748106:web:7edf6548e201aa2b3437b3',
    messagingSenderId: '162628748106',
    projectId: 'locator-4f6ba',
    authDomain: 'locator-4f6ba.firebaseapp.com',
    databaseURL: 'https://locator-4f6ba-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'locator-4f6ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC574kPsV8hwLj2nZKFJQen7m-4yZTBa3Q',
    appId: '1:162628748106:android:7e89768dd280aadf3437b3',
    messagingSenderId: '162628748106',
    projectId: 'locator-4f6ba',
    databaseURL: 'https://locator-4f6ba-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'locator-4f6ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj2Ae_frJBjNpEi71E8qzEEWmK5meIGoQ',
    appId: '1:162628748106:ios:060de25cac27cbef3437b3',
    messagingSenderId: '162628748106',
    projectId: 'locator-4f6ba',
    databaseURL: 'https://locator-4f6ba-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'locator-4f6ba.appspot.com',
    iosClientId: '162628748106-c81r86ttrl29af9bie8lg2kg6p1o0b8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.locator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj2Ae_frJBjNpEi71E8qzEEWmK5meIGoQ',
    appId: '1:162628748106:ios:060de25cac27cbef3437b3',
    messagingSenderId: '162628748106',
    projectId: 'locator-4f6ba',
    databaseURL: 'https://locator-4f6ba-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'locator-4f6ba.appspot.com',
    iosClientId: '162628748106-c81r86ttrl29af9bie8lg2kg6p1o0b8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.locator',
  );
}
